[package]
name = "automaTom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "*"
rlua = { version = "0.19.7" }
rand = "0.8.4"
serde = { version = "*", features = ["derive"] }
toml = "*"